### GET List of tasks

GET http://localhost:8080/tasks?from=2000-02-04T22:18:52.616933&to=2028-02-04T22:18:52.616933&userId=777

### GET tasks for id

GET http://localhost:8080/tasks/1

### POST create new tasks

POST http://localhost:8080/tasks
Content-Type: application/json

{
  "title": "Сделать дела",
  "status": "IN_PROGRESS",
  "createdBy": 777
}

### PUT update task

PUT http://localhost:8080/tasks/2
Content-Type: application/json

{
  "title": "Сделать дела",
  "status": "DONE"
}

### DELETE task

DELETE http://localhost:8080/tasks/15

### GET count active task

GET http://localhost:8080/tasks/active/count?userId=777
Accept: application/json
