### Регистрация пользователя
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "user1",
  "password": "user1"
}

### Login (Basic Auth)
GET http://localhost:8080/auth/me
Authorization: Basic RmRzZmhzZGo6c2RuZmZrbnNka2Y=
// username:password
# (логин:пароль в base64)

### Login (Form) - сначала нужно получить cookie
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = Fdsfhsdj &
password = sdnffknsdkf

