### Регистрация пользователя
POST http://localhost:8080/users/register
Content-Type: application/json

{
  "username": "Fdsfhsdj",
  "password": "sdnffknsdkf"
}

### Login (Basic Auth)
GET http://localhost:8080/auth/me
Authorization: Basic RmRzZmhzZGo6c2RuZmZrbnNka2Y=
# (логин:пароль в base64)

### Login (Form) - сначала нужно получить cookie
POST http://localhost:8080/login
Content-Type: application/x-www-form-urlencoded

username = Fdsfhsdj &
password = sdnffknsdkf

### Создание задачи (с токеном или сессией)
POST http://localhost:8080/tasks
Content-Type: application/json
Authorization: Bearer <ваш_токен>
# или Cookie: JSESSIONID=<ваш_id>

{
  "title": "Новая задача",
  "status": "OPEN"
}